export type TemplateSection = {
  id: string;
  type: 'text' | 'feature' | 'contact';
  title: string;
  body?: string;
  bullets?: string[];
  imageUrl?: string;
};

export type PortfolioTemplate = {
  slug: string;
  name: string;
  category: string;
  theme: 'dark' | 'light';
  description: string;
  heroTitle: string;
  heroSubtitle: string;
  highlights: string[];
  sections: TemplateSection[];
  tags: string[];
};

export const templates: PortfolioTemplate[] = [
  {
    slug: 'developer-pro',
    name: 'Developer Pro',
    category: 'Developer',
    theme: 'dark',
    description: 'A modern developer portfolio built for apps, APIs, and product launches.',
    heroTitle: 'Build fast, scalable products with precision.',
    heroSubtitle: 'Showcase your technical craft, side projects, and developer story in a clean, powerful layout.',
    highlights: ['Project case studies', 'Skill matrix', 'Live code sections'],
    tags: ['Developer', 'Dark', 'Tech', 'Minimal'],
    sections: [
      {
        id: 'dev-about',
        type: 'text',
        title: 'About Me',
        body: 'I design and build products that scale across web and mobile. My work focuses on performance, accessibility, and delightful developer experiences.',
      },
      {
        id: 'dev-projects',
        type: 'feature',
        title: 'Featured Projects',
        bullets: ['AI dashboard with real-time analytics', 'Serverless e-commerce checkout', 'Open-source design system'],
      },
      {
        id: 'dev-skills',
        type: 'feature',
        title: 'Core Skills',
        bullets: ['TypeScript', 'React', 'Node.js', 'GraphQL', 'Cloud Architecture'],
      },
      {
        id: 'dev-contact',
        type: 'contact',
        title: 'Contact',
        body: 'Let’s build your next digital product together. Ready when you are.',
      },
    ],
  },
  {
    slug: 'designer-studio',
    name: 'Designer Studio',
    category: 'Designer',
    theme: 'light',
    description: 'A polished portfolio for visual designers, product creatives, and brand builders.',
    heroTitle: 'Design systems that feel modern and intuitive.',
    heroSubtitle: 'Present your brand work, case studies, and process with a refined studio presence.',
    highlights: ['Artwork grid', 'Story-driven case studies', 'Visual timeline'],
    tags: ['Designer', 'Light', 'Creative', 'Portfolio'],
    sections: [
      {
        id: 'studio-about',
        type: 'text',
        title: 'Designer Story',
        body: 'I craft memorable brand and product experiences with a focus on clarity, accessibility, and motion.',
      },
      {
        id: 'studio-works',
        type: 'feature',
        title: 'Selected Work',
        bullets: ['Brand identity for premium startups', 'Landing pages with high conversion', 'Mobile app UI systems'],
      },
      {
        id: 'studio-services',
        type: 'feature',
        title: 'Services',
        bullets: ['Visual design', 'UX strategy', 'Brand refresh', 'Design systems'],
      },
      {
        id: 'studio-contact',
        type: 'contact',
        title: 'Let’s collaborate',
        body: 'I help teams bring ambitious ideas to life through thoughtful design and execution.',
      },
    ],
  },
  {
    slug: 'photographer-essence',
    name: 'Photographer Essence',
    category: 'Photographer',
    theme: 'dark',
    description: 'A dramatic photography showcase for portfolios, galleries, and editorial projects.',
    heroTitle: 'Capture light, mood, and storytelling in every frame.',
    heroSubtitle: 'Display your best work and client stories in a luxurious gallery-first format.',
    highlights: ['Gallery collections', 'Client testimonials', 'Booking details'],
    tags: ['Photographer', 'Dark', 'Luxury', 'Visual'],
    sections: [
      {
        id: 'photo-about',
        type: 'text',
        title: 'About the Artist',
        body: 'I specialize in editorial, lifestyle, and commercial photography with a cinematic visual language.',
      },
      {
        id: 'photo-gallery',
        type: 'feature',
        title: 'Featured Shoots',
        bullets: ['Fashion campaign for premium brands', 'Hotel lifestyle imagery', 'Creative portraits and travel stories'],
      },
      {
        id: 'photo-services',
        type: 'feature',
        title: 'Photography Services',
        bullets: ['Editorial direction', 'Commercial campaigns', 'Portrait sessions', 'Event coverage'],
      },
      {
        id: 'photo-contact',
        type: 'contact',
        title: 'Book a session',
        body: 'Available for commissions, brand partnerships, and creative collaborations worldwide.',
      },
    ],
  },
  {
    slug: 'business-growth',
    name: 'Business Growth',
    category: 'Business',
    theme: 'light',
    description: 'A conversion-focused portfolio for consultants, executives, and B2B services.',
    heroTitle: 'Scale your business with clarity and trust.',
    heroSubtitle: 'Present your services, metrics, and client results in a premium business layout.',
    highlights: ['Metrics-driven case studies', 'Service plans', 'Client logos'],
    tags: ['Business', 'Corporate', 'Light', 'Professional'],
    sections: [
      {
        id: 'business-about',
        type: 'text',
        title: 'Executive Summary',
        body: 'I partner with fast-growing companies to improve revenue, operations, and customer experiences through measurable strategy.',
      },
      {
        id: 'business-results',
        type: 'feature',
        title: 'Key Results',
        bullets: ['Improved conversion by 42%', 'Optimized product launch strategy', 'Scaled customer onboarding experiences'],
      },
      {
        id: 'business-services',
        type: 'feature',
        title: 'Advisory Services',
        bullets: ['Business strategy', 'Product positioning', 'Go-to-market planning', 'Executive coaching'],
      },
      {
        id: 'business-contact',
        type: 'contact',
        title: 'Let’s talk growth',
        body: 'Ready to shape your next revenue milestone with a tailored growth plan.',
      },
    ],
  },
  {
    slug: 'minimal-modern',
    name: 'Minimal Modern',
    category: 'Minimal',
    theme: 'light',
    description: 'A clean, understated portfolio with crisp typography and intentional white space.',
    heroTitle: 'Bold ideas presented with elegant simplicity.',
    heroSubtitle: 'Perfect for creators who want a refined and distraction-free personal brand.',
    highlights: ['Minimal sections', 'Clear hierarchy', 'Fast loading'],
    tags: ['Minimal', 'Light', 'Clean', 'Modern'],
    sections: [
      {
        id: 'minimal-about',
        type: 'text',
        title: 'About Me',
        body: 'I champion thoughtful design and meaningful storytelling through a minimal aesthetic.',
      },
      {
        id: 'minimal-projects',
        type: 'feature',
        title: 'Projects',
        bullets: ['Brand identity system', 'Web product launch', 'Editorial design series'],
      },
      {
        id: 'minimal-services',
        type: 'feature',
        title: 'Capabilities',
        bullets: ['Creative direction', 'Brand strategy', 'Product design', 'Visual storytelling'],
      },
      {
        id: 'minimal-contact',
        type: 'contact',
        title: 'Work together',
        body: 'Let’s create something calm, clear, and memorable.',
      },
    ],
  },
  {
    slug: 'luxury-brand',
    name: 'Luxury Brand',
    category: 'Luxury',
    theme: 'dark',
    description: 'A high-end portfolio with elegant styling for premium brands and creative directors.',
    heroTitle: 'Premium experiences built for distinctive brands.',
    heroSubtitle: 'Showcase your most sophisticated work with a luxurious, editorial presentation.',
    highlights: ['Elegant typography', 'Premium imagery', 'Brand storytelling'],
    tags: ['Luxury', 'Dark', 'Premium', 'Editorial'],
    sections: [
      {
        id: 'luxury-about',
        type: 'text',
        title: 'About the Creative Director',
        body: 'I partner with luxury brands to design timeless experiences that elevate every touchpoint.',
      },
      {
        id: 'luxury-work',
        type: 'feature',
        title: 'Signature Work',
        bullets: ['Retail environment campaigns', 'High-end editorial direction', 'Luxury product launches'],
      },
      {
        id: 'luxury-services',
        type: 'feature',
        title: 'Capabilities',
        bullets: ['Brand design', 'Campaign strategy', 'Experience design'],
      },
      {
        id: 'luxury-contact',
        type: 'contact',
        title: 'Book a consultation',
        body: 'Elevate your brand with a premium creative partner who cares about every detail.',
      },
    ],
  },
  {
    slug: 'cyber-edge',
    name: 'Cyber Edge',
    category: 'Cyber',
    theme: 'dark',
    description: 'An energetic portfolio for cybersecurity experts, e-sports creators, and futuristic brands.',
    heroTitle: 'Designing digital experiences with a cyber edge.',
    heroSubtitle: 'Amplify your work with bold gradients, motion-ready sections, and sharp details.',
    highlights: ['Tech-forward styling', 'Service showcase', 'Project strengths'],
    tags: ['Cyber', 'Dark', 'Futuristic', 'Tech'],
    sections: [
      {
        id: 'cyber-about',
        type: 'text',
        title: 'Who I am',
        body: 'I build security-conscious digital products and immersive experiences for future-facing brands.',
      },
      {
        id: 'cyber-projects',
        type: 'feature',
        title: 'What I build',
        bullets: ['Secure SaaS platforms', 'Digital product launches', 'Futuristic brand experiences'],
      },
      {
        id: 'cyber-skills',
        type: 'feature',
        title: 'Core strengths',
        bullets: ['Security architecture', 'UX for complex systems', 'Rapid prototyping'],
      },
      {
        id: 'cyber-contact',
        type: 'contact',
        title: 'Partner with me',
        body: 'Let’s turn your boldest ideas into secure digital products.',
      },
    ],
  },
  {
    slug: 'glass-portfolio',
    name: 'Glass Portfolio',
    category: 'Glass',
    theme: 'light',
    description: 'A sleek portfolio that uses glassmorphism and translucency to create a premium feel.',
    heroTitle: 'A luminous space for your most polished work.',
    heroSubtitle: 'Present your portfolio with elegant glass surfaces, depth, and modern polish.',
    highlights: ['Glass-inspired design', 'Clean sections', 'Premium motion accents'],
    tags: ['Glass', 'Light', 'Premium', 'Modern'],
    sections: [
      {
        id: 'glass-about',
        type: 'text',
        title: 'About My Work',
        body: 'I create polished brand and product experiences that feel luxurious and inviting.',
      },
      {
        id: 'glass-showcase',
        type: 'feature',
        title: 'Portfolio Highlights',
        bullets: ['Brand systems', 'Product launches', 'Interactive digital experiences'],
      },
      {
        id: 'glass-process',
        type: 'feature',
        title: 'Design approach',
        bullets: ['Concept strategy', 'Visual storytelling', 'Refined execution'],
      },
      {
        id: 'glass-contact',
        type: 'contact',
        title: 'Start a conversation',
        body: 'If you value elegant design and thoughtful execution, let’s connect.',
      },
    ],
  },
  {
    slug: 'ai-innovator',
    name: 'AI Innovator',
    category: 'AI',
    theme: 'dark',
    description: 'A futuristic portfolio built for AI founders, machine learning specialists, and research labs.',
    heroTitle: 'Showcase intelligent products and AI research with clarity.',
    heroSubtitle: 'Share your data-driven story, product vision, and technical proof points in a modern format.',
    highlights: ['AI case studies', 'Research highlights', 'Product demos'],
    tags: ['AI', 'Dark', 'Futuristic', 'Research'],
    sections: [
      {
        id: 'ai-about',
        type: 'text',
        title: 'AI Focus',
        body: 'I bring advanced ai, data science, and product design together to launch powerful intelligent products.',
      },
      {
        id: 'ai-projects',
        type: 'feature',
        title: 'Featured work',
        bullets: ['Personalization engine', 'Intelligent automation platform', 'ML-driven analytics'],
      },
      {
        id: 'ai-technologies',
        type: 'feature',
        title: 'Tech stack',
        bullets: ['Python', 'TensorFlow', 'Prompt engineering', 'Cloud AI infrastructure'],
      },
      {
        id: 'ai-contact',
        type: 'contact',
        title: 'Build the next AI experience',
        body: 'I’m available for AI product design, research direction, and strategic launches.',
      },
    ],
  },
  {
    slug: 'creative-studio',
    name: 'Creative Studio',
    category: 'Creative',
    theme: 'light',
    description: 'A vibrant portfolio for creative studios, directors, and brand consultants.',
    heroTitle: 'Turn ideas into memorable creative expressions.',
    heroSubtitle: 'Share your best work and the strategic thinking behind it with visual confidence.',
    highlights: ['Studio showcase', 'Creative process', 'Client stories'],
    tags: ['Creative', 'Light', 'Studio', 'Brand'],
    sections: [
      {
        id: 'creative-about',
        type: 'text',
        title: 'Studio identity',
        body: 'We create powerful visual narratives, campaigns, and experiences for ambitious brands.',
      },
      {
        id: 'creative-work',
        type: 'feature',
        title: 'Recent projects',
        bullets: ['Campaign design for lifestyle brands', 'Interactive storytelling experiences', 'Brand identity systems'],
      },
      {
        id: 'creative-services',
        type: 'feature',
        title: 'What we offer',
        bullets: ['Creative direction', 'Brand storytelling', 'Content strategy', 'Design systems'],
      },
      {
        id: 'creative-contact',
        type: 'contact',
        title: 'Collaborate on creative work',
        body: 'Let’s bring your brand story to life with a bold creative approach.',
      },
    ],
  },
  {
    slug: 'corporate-executive',
    name: 'Corporate Executive',
    category: 'Corporate',
    theme: 'light',
    description: 'A polished portfolio for executives, consultants, and corporate leaders.',
    heroTitle: 'A refined profile for leaders shaping business transformation.',
    heroSubtitle: 'Bring credibility, experience, and leadership impact forward in a clean corporate layout.',
    highlights: ['Executive bio', 'Board experience', 'Leadership outcomes'],
    tags: ['Corporate', 'Light', 'Executive', 'Professional'],
    sections: [
      {
        id: 'corp-about',
        type: 'text',
        title: 'Professional background',
        body: 'I lead teams that deliver measurable business results through strategy, growth, and operational excellence.',
      },
      {
        id: 'corp-results',
        type: 'feature',
        title: 'Leadership outcomes',
        bullets: ['Scaled revenue by 80%', 'Built teams across three continents', 'Launched enterprise products'],
      },
      {
        id: 'corp-services',
        type: 'feature',
        title: 'Advisory focus',
        bullets: ['Growth strategy', 'Operational transformation', 'Executive coaching'],
      },
      {
        id: 'corp-contact',
        type: 'contact',
        title: 'Speak with me',
        body: 'I’m available for advisory, speaking, and executive coaching opportunities.',
      },
    ],
  },
  {
    slug: 'student-showcase',
    name: 'Student Showcase',
    category: 'Student',
    theme: 'light',
    description: 'A fresh, approachable portfolio for students and new graduates showcasing work and ambitions.',
    heroTitle: 'Your story starts here with crisp presentation and purpose.',
    heroSubtitle: 'Highlight your projects, skills, and the value you bring to your next team.',
    highlights: ['Project showcases', 'Skills list', 'Graduate profile'],
    tags: ['Student', 'Light', 'Fresh', 'Career'],
    sections: [
      {
        id: 'student-about',
        type: 'text',
        title: 'About Me',
        body: 'I am a recent graduate focused on product design, front-end development, and brand experiences.',
      },
      {
        id: 'student-projects',
        type: 'feature',
        title: 'Academic work',
        bullets: ['Capstone project on UX design', 'Interactive web application', 'Brand refresh concept'],
      },
      {
        id: 'student-skills',
        type: 'feature',
        title: 'Skillset',
        bullets: ['React', 'Figma', 'Visual storytelling', 'Collaboration'],
      },
      {
        id: 'student-contact',
        type: 'contact',
        title: 'Let’s connect',
        body: 'I’m eager to join a team where I can continue learning and contribute to strong digital products.',
      },
    ],
  },
  {
    slug: 'freelancer-hub',
    name: 'Freelancer Hub',
    category: 'Freelancer',
    theme: 'dark',
    description: 'A confident portfolio for freelancers who need a direct, persuasive presentation.',
    heroTitle: 'A professional hub for freelance work and client stories.',
    heroSubtitle: 'Share your best projects, testimonials, and service packages in one place.',
    highlights: ['Commission packages', 'Testimonials', 'Service offerings'],
    tags: ['Freelancer', 'Dark', 'Professional', 'Direct'],
    sections: [
      {
        id: 'freelancer-about',
        type: 'text',
        title: 'Who I serve',
        body: 'I work with startups and small businesses to deliver polished digital experiences on time and on budget.',
      },
      {
        id: 'freelancer-projects',
        type: 'feature',
        title: 'Recent work',
        bullets: ['Brand refresh for creative studio', 'Marketing website redesign', 'Product launch campaign'],
      },
      {
        id: 'freelancer-services',
        type: 'feature',
        title: 'Available services',
        bullets: ['Freelance design', 'Web development', 'Brand strategy', 'Digital marketing collateral'],
      },
      {
        id: 'freelancer-contact',
        type: 'contact',
        title: 'Start your project',
        body: 'Let’s talk about how I can help you build the right digital experience.',
      },
    ],
  },
  {
    slug: 'dark-vision',
    name: 'Dark Vision',
    category: 'Dark',
    theme: 'dark',
    description: 'A moody dark portfolio with strong contrast and modern layout for creative professionals.',
    heroTitle: 'Bold, dark design for standout portfolios.',
    heroSubtitle: 'Make your skills and work feel cinematic with dramatic styling and crisp type.',
    highlights: ['High contrast design', 'Bold typography', 'Immersive storytelling'],
    tags: ['Dark', 'Bold', 'Cinematic', 'Creative'],
    sections: [
      {
        id: 'dark-about',
        type: 'text',
        title: 'Creative focus',
        body: 'I create immersive digital and visual experiences with a dark, polished aesthetic.',
      },
      {
        id: 'dark-work',
        type: 'feature',
        title: 'Portfolio highlights',
        bullets: ['Brand experience design', 'Digital publication', 'Visual systems'],
      },
      {
        id: 'dark-skills',
        type: 'feature',
        title: 'Capabilities',
        bullets: ['Creative strategy', 'Digital design', 'Motion direction'],
      },
      {
        id: 'dark-contact',
        type: 'contact',
        title: 'Work with me',
        body: 'I’m available for projects that need a refined visual identity and bold storytelling.',
      },
    ],
  },
  {
    slug: 'light-breeze',
    name: 'Light Breeze',
    category: 'Light',
    theme: 'light',
    description: 'A bright, airy portfolio perfect for lifestyle brands and professional creatives.',
    heroTitle: 'A light portfolio designed for warmth and clarity.',
    heroSubtitle: 'Show your personality, work, and services with a welcoming layout.',
    highlights: ['Soft visuals', 'Approachable sections', 'Clear messaging'],
    tags: ['Light', 'Bright', 'Approachable', 'Lifestyle'],
    sections: [
      {
        id: 'light-about',
        type: 'text',
        title: 'About Me',
        body: 'I create approachable digital experiences with a focus on storytelling and human-centered design.',
      },
      {
        id: 'light-projects',
        type: 'feature',
        title: 'Recent work',
        bullets: ['Lifestyle brand launch', 'Content-driven website', 'Creative portfolio redesign'],
      },
      {
        id: 'light-services',
        type: 'feature',
        title: 'Services',
        bullets: ['Brand storytelling', 'Visual design', 'Web experiences', 'Content strategy'],
      },
      {
        id: 'light-contact',
        type: 'contact',
        title: 'Say hello',
        body: 'Interested in a project? I’m ready to collaborate on thoughtful digital experiences.',
      },
    ],
  },
  {
    slug: 'animated-flow',
    name: 'Animated Flow',
    category: 'Animated',
    theme: 'dark',
    description: 'A motion-rich portfolio with animated sections and a dynamic first impression.',
    heroTitle: 'Bring your portfolio to life with motion and dynamism.',
    heroSubtitle: 'A highly visual layout designed for motion designers and interactive storytellers.',
    highlights: ['Motion-first presentation', 'Interaction cues', 'Dynamic case studies'],
    tags: ['Animated', 'Motion', 'Dynamic', 'Interactive'],
    sections: [
      {
        id: 'animated-about',
        type: 'text',
        title: 'Motion designer',
        body: 'I create animated experiences, brand motion systems, and interactive storytelling for digital touchpoints.',
      },
      {
        id: 'animated-work',
        type: 'feature',
        title: 'Motion work',
        bullets: ['Interactive brand launch', 'Animation system design', 'Video-first storytelling'],
      },
      {
        id: 'animated-process',
        type: 'feature',
        title: 'How I work',
        bullets: ['Concept development', 'Animation direction', 'Interactive prototyping'],
      },
      {
        id: 'animated-contact',
        type: 'contact',
        title: 'Collaborate on motion',
        body: 'Let’s create motion-driven experiences that feel polished and engaging.',
      },
    ],
  },
  {
    slug: 'product-designer',
    name: 'Product Designer',
    category: 'Designer',
    theme: 'light',
    description: 'A modern portfolio for product designers, UX leads, and interface creators.',
    heroTitle: 'Design thoughtful product experiences with clarity.',
    heroSubtitle: 'Share your process, research, and product thinking in a beautifully crafted portfolio.',
    highlights: ['Product case studies', 'Design process', 'UX research'],
    tags: ['Designer', 'Light', 'Product', 'UX'],
    sections: [
      {
        id: 'product-about',
        type: 'text',
        title: 'Design practice',
        body: 'I build digital products that balance user needs, business goals, and elegant interfaces.',
      },
      {
        id: 'product-case-studies',
        type: 'feature',
        title: 'Case studies',
        bullets: ['Product redesign for SaaS', 'User research-led interface', 'Cross-platform design system'],
      },
      {
        id: 'product-skills',
        type: 'feature',
        title: 'Tools & skills',
        bullets: ['Figma', 'Research', 'Interaction design', 'Prototyping', 'Design systems'],
      },
      {
        id: 'product-contact',
        type: 'contact',
        title: 'Work together',
        body: 'I’m open to product design partnerships, leadership roles, and collaborative projects.',
      },
    ],
  },
  {
    slug: 'consultant-elite',
    name: 'Consultant Elite',
    category: 'Business',
    theme: 'dark',
    description: 'A premium consultant portfolio with results-oriented messaging and trust signals.',
    heroTitle: 'Consulting that drives measurable business outcomes.',
    heroSubtitle: 'Showcase your expertise with a polished, executive-level portfolio.',
    highlights: ['Results summary', 'Services portfolio', 'Trust credentials'],
    tags: ['Business', 'Dark', 'Consultant', 'Professional'],
    sections: [
      {
        id: 'consultant-about',
        type: 'text',
        title: 'Consulting focus',
        body: 'I help leadership teams align product, growth, and operations for scalable success.',
      },
      {
        id: 'consultant-results',
        type: 'feature',
        title: 'Consulting outcomes',
        bullets: ['Revenue uplift with strategic planning', 'Operational efficiency redesign', 'Go-to-market acceleration'],
      },
      {
        id: 'consultant-services',
        type: 'feature',
        title: 'Offerings',
        bullets: ['Strategy workshops', 'Executive advisory', 'Transformation roadmaps'],
      },
      {
        id: 'consultant-contact',
        type: 'contact',
        title: 'Book a session',
        body: 'Let’s explore how we can move your business forward with confidence.',
      },
    ],
  },
  {
    slug: 'agency-collective',
    name: 'Agency Collective',
    category: 'Creative',
    theme: 'light',
    description: 'A collaborative agency portfolio for teams and studios with a strong creative identity.',
    heroTitle: 'A collective portfolio for standout creative work.',
    heroSubtitle: 'Showcase your studio’s best campaigns, services, and client partnerships.',
    highlights: ['Team showcases', 'Studio services', 'Client testimonials'],
    tags: ['Creative', 'Light', 'Agency', 'Studio'],
    sections: [
      {
        id: 'agency-about',
        type: 'text',
        title: 'About the studio',
        body: 'We are a creative agency focused on brand and digital experiences that resonate with audiences.',
      },
      {
        id: 'agency-work',
        type: 'feature',
        title: 'Studio work',
        bullets: ['Integrated campaigns', 'Product launch identities', 'Performance-driven creative'],
      },
      {
        id: 'agency-services',
        type: 'feature',
        title: 'Capabilities',
        bullets: ['Creative direction', 'Brand systems', 'Digital activation'],
      },
      {
        id: 'agency-contact',
        type: 'contact',
        title: 'Partner with us',
        body: 'We help teams create memorable brand and digital experiences.',
      },
    ],
  },
  {
    slug: 'nomad-visionary',
    name: 'Digital Nomad',
    category: 'Freelancer',
    theme: 'light',
    description: 'A dynamic portfolio for remote freelancers and digital nomads who travel with purpose.',
    heroTitle: 'A portfolio for the modern remote creative.',
    heroSubtitle: 'Highlight your adaptable skills, client work, and remote-friendly approach.',
    highlights: ['Remote work profile', 'Flexible services', 'Project highlights'],
    tags: ['Freelancer', 'Light', 'Remote', 'Nomad'],
    sections: [
      {
        id: 'nomad-about',
        type: 'text',
        title: 'Remote creator',
        body: 'I deliver compelling digital experiences from anywhere, working with clients across borders.',
      },
      {
        id: 'nomad-projects',
        type: 'feature',
        title: 'Remote portfolio',
        bullets: ['Cross-border product launches', 'Remote brand campaigns', 'Digital marketing systems'],
      },
      {
        id: 'nomad-services',
        type: 'feature',
        title: 'Offered services',
        bullets: ['Remote design', 'Web development', 'Brand strategy', 'Digital product consulting'],
      },
      {
        id: 'nomad-contact',
        type: 'contact',
        title: 'Work with me remotely',
        body: 'I’m available for remote projects that value reliability, creativity, and agility.',
      },
    ],
  },
  {
    slug: 'marketing-maven',
    name: 'Marketing Maven',
    category: 'Business',
    theme: 'light',
    description: 'A portfolio for marketing professionals who want to present campaigns, metrics, and strategy clearly.',
    heroTitle: 'Show your marketing work with confidence and clarity.',
    heroSubtitle: 'The ideal portfolio for campaign strategists, growth marketers, and brand storytellers.',
    highlights: ['Campaign highlights', 'Performance metrics', 'Strategic offerings'],
    tags: ['Business', 'Light', 'Marketing', 'Growth'],
    sections: [
      {
        id: 'marketing-about',
        type: 'text',
        title: 'Marketing strategy',
        body: 'I help brands build memorable campaigns and measurable growth through data-informed strategy.',
      },
      {
        id: 'marketing-work',
        type: 'feature',
        title: 'Campaign highlights',
        bullets: ['Brand awareness campaigns', 'Performance-driven launches', 'Content strategy systems'],
      },
      {
        id: 'marketing-services',
        type: 'feature',
        title: 'Services',
        bullets: ['Growth marketing', 'Paid media', 'Content planning', 'Brand storytelling'],
      },
      {
        id: 'marketing-contact',
        type: 'contact',
        title: 'Let’s grow your brand',
        body: 'I’m ready to partner on strategic marketing work that delivers results.',
      },
    ],
  },
  {
    slug: 'ux-specialist',
    name: 'UX Specialist',
    category: 'Designer',
    theme: 'dark',
    description: 'A focused portfolio for UX researchers and experience designers with process-first storytelling.',
    heroTitle: 'Map engaging experiences with thoughtful research and design.',
    heroSubtitle: 'Highlight your UX process, case studies, and impact with a clear, professional layout.',
    highlights: ['Research highlights', 'Journey maps', 'Design systems'],
    tags: ['Designer', 'Dark', 'UX', 'Research'],
    sections: [
      {
        id: 'ux-about',
        type: 'text',
        title: 'UX practice',
        body: 'I design digital products from first principles, combining research, usability, and visual clarity.',
      },
      {
        id: 'ux-projects',
        type: 'feature',
        title: 'Experience work',
        bullets: ['Research-led product design', 'Interface optimization', 'Accessibility-focused systems'],
      },
      {
        id: 'ux-methods',
        type: 'feature',
        title: 'Approach',
        bullets: ['Research', 'Interaction design', 'Prototyping', 'Testing'],
      },
      {
        id: 'ux-contact',
        type: 'contact',
        title: 'Collaborate on UX',
        body: 'I’m available for UX and experience design projects that shape meaningful products.',
      },
    ],
  },
  {
    slug: 'architecture-portfolio',
    name: 'Architecture Studio',
    category: 'Creative',
    theme: 'light',
    description: 'A sophisticated portfolio for architects, interior designers, and built environment studios.',
    heroTitle: 'Showcase architectural vision with elegant presentation.',
    heroSubtitle: 'A portfolio layout suited for spatial design, built work, and creative direction.',
    highlights: ['Built projects', 'Design process', 'Studio philosophy'],
    tags: ['Creative', 'Light', 'Architecture', 'Design'],
    sections: [
      {
        id: 'architecture-about',
        type: 'text',
        title: 'Studio narrative',
        body: 'We design thoughtful spaces and visual experiences rooted in craftsmanship and context.',
      },
      {
        id: 'architecture-projects',
        type: 'feature',
        title: 'Featured projects',
        bullets: ['Residential architecture', 'Commercial interior environments', 'Brand experience design'],
      },
      {
        id: 'architecture-services',
        type: 'feature',
        title: 'Our services',
        bullets: ['Architecture design', 'Spatial planning', 'Concept development', 'Creative direction'],
      },
      {
        id: 'architecture-contact',
        type: 'contact',
        title: 'Partner with us',
        body: 'We work with clients who want a refined approach to spatial and experiential design.',
      },
    ],
  },
  {
    slug: 'event-photographer',
    name: 'Event Photographer',
    category: 'Photographer',
    theme: 'light',
    description: 'A bright and polished portfolio for event photographers and lifestyle storytellers.',
    heroTitle: 'Deliver memorable event photography with style and clarity.',
    heroSubtitle: 'Showcase your best weddings, conferences, and lifestyle sessions with a compelling portfolio.',
    highlights: ['Event galleries', 'Client experience', 'Booking details'],
    tags: ['Photographer', 'Light', 'Events', 'Lifestyle'],
    sections: [
      {
        id: 'event-about',
        type: 'text',
        title: 'Event photography',
        body: 'I capture authentic moments from events with a polished editorial and lifestyle aesthetic.',
      },
      {
        id: 'event-work',
        type: 'feature',
        title: 'Event highlights',
        bullets: ['Weddings', 'Corporate conferences', 'Lifestyle gatherings'],
      },
      {
        id: 'event-services',
        type: 'feature',
        title: 'Services',
        bullets: ['Event coverage', 'Editorial sessions', 'Photography direction'],
      },
      {
        id: 'event-contact',
        type: 'contact',
        title: 'Book your event',
        body: 'I’m available for event, lifestyle, and editorial photography projects.',
      },
    ],
  },
  {
    slug: 'brand-strategist',
    name: 'Brand Strategist',
    category: 'Business',
    theme: 'dark',
    description: 'A confident portfolio for brand strategists and identity consultants.',
    heroTitle: 'Build brands that connect and scale.',
    heroSubtitle: 'Present your strategy, positioning, and work with a premium portfolio layout.',
    highlights: ['Brand strategy', 'Positioning frameworks', 'Creative campaigns'],
    tags: ['Business', 'Dark', 'Brand', 'Strategy'],
    sections: [
      {
        id: 'brand-about',
        type: 'text',
        title: 'Strategic brand work',
        body: 'I help brands define identity, positioning, and messaging that make a meaningful impact.',
      },
      {
        id: 'brand-work',
        type: 'feature',
        title: 'Strategic projects',
        bullets: ['Rebrand for modern consumer businesses', 'Positioning for growth-stage products', 'Brand launch systems'],
      },
      {
        id: 'brand-services',
        type: 'feature',
        title: 'What I do',
        bullets: ['Brand strategy', 'Identity systems', 'Market positioning'],
      },
      {
        id: 'brand-contact',
        type: 'contact',
        title: 'Talk strategy',
        body: 'Ready to define your next brand chapter? Let’s talk.',
      },
    ],
  },
  {
    slug: 'visual-storyteller',
    name: 'Visual Storyteller',
    category: 'Creative',
    theme: 'dark',
    description: 'A narrative portfolio for storytellers, filmmakers, and visual directors.',
    heroTitle: 'Tell your story with beautiful visuals and compelling structure.',
    heroSubtitle: 'A portfolio built for cinematic storytelling and creative direction.',
    highlights: ['Story-driven work', 'Creative process', 'Audience impact'],
    tags: ['Creative', 'Dark', 'Storytelling', 'Film'],
    sections: [
      {
        id: 'visual-about',
        type: 'text',
        title: 'Narrative practice',
        body: 'I craft visual stories that connect emotional ideas with strong creative execution.',
      },
      {
        id: 'visual-projects',
        type: 'feature',
        title: 'Featured work',
        bullets: ['Film direction', 'Visual campaigns', 'Story-driven web experiences'],
      },
      {
        id: 'visual-services',
        type: 'feature',
        title: 'Offerings',
        bullets: ['Story direction', 'Creative consulting', 'Visual strategy'],
      },
      {
        id: 'visual-contact',
        type: 'contact',
        title: 'Create with me',
        body: 'I’m available for projects that need strong storytelling and visual craftsmanship.',
      },
    ],
  },
  {
    slug: 'startup-founder',
    name: 'Startup Founder',
    category: 'Business',
    theme: 'light',
    description: 'A bold portfolio for founders, product leaders, and startup operators.',
    heroTitle: 'Present your startup journey, product vision, and leadership experience.',
    heroSubtitle: 'A clean, high-impact portfolio for founders and operators building in tech.',
    highlights: ['Founder story', 'Product roadmap', 'Leadership experience'],
    tags: ['Business', 'Light', 'Founder', 'Startup'],
    sections: [
      {
        id: 'startup-about',
        type: 'text',
        title: 'Founder story',
        body: 'I build and scale digital products with teams that prioritize user value and growth.',
      },
      {
        id: 'startup-work',
        type: 'feature',
        title: 'Company milestones',
        bullets: ['Product launches', 'Growth initiatives', 'Team building'],
      },
      {
        id: 'startup-services',
        type: 'feature',
        title: 'What I do',
        bullets: ['Product leadership', 'Startup strategy', 'Founders coaching'],
      },
      {
        id: 'startup-contact',
        type: 'contact',
        title: 'Talk product',
        body: 'I’m open to advisory and founder roles for ambitious startups.',
      },
    ],
  },
  {
    slug: 'content-creator',
    name: 'Content Creator',
    category: 'Creative',
    theme: 'light',
    description: 'A portfolio for content creators, digital storytellers, and brand collaborators.',
    heroTitle: 'Showcase your digital content with a creative, polished presentation.',
    heroSubtitle: 'Perfect for writers, creators, and marketers who want an approachable portfolio.',
    highlights: ['Content showcase', 'Media channels', 'Creative services'],
    tags: ['Creative', 'Light', 'Content', 'Storytelling'],
    sections: [
      {
        id: 'content-about',
        type: 'text',
        title: 'Creator focus',
        body: 'I create engaging digital content that connects with audiences across channels.',
      },
      {
        id: 'content-work',
        type: 'feature',
        title: 'Featured content',
        bullets: ['Editorial campaigns', 'Brand storytelling', 'Social-first content'],
      },
      {
        id: 'content-services',
        type: 'feature',
        title: 'Services',
        bullets: ['Content strategy', 'Copywriting', 'Digital storytelling'],
      },
      {
        id: 'content-contact',
        type: 'contact',
        title: 'Let’s collaborate',
        body: 'I’m interested in projects that need strong messaging and creative content.',
      },
    ],
  },
];

export function getTemplateBySlug(slug: string) {
  return templates.find((template) => template.slug === slug);
}

export const templateCategories = Array.from(
  new Set(templates.map((template) => template.category))
).sort();
